# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: myblog_development

test:
  <<: *default
  database: myblog_test

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: pictweet_production
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock
